# Generated by Django 3.2.7 on 2021-10-31 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.TextField(default='')),
                ('nick_name', models.TextField(default='')),
                ('password', models.TextField(default='')),
                ('head_photo', models.CharField(max_length=65536)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(default='')),
                ('artist', models.TextField(default='')),
                ('duration', models.TextField(default='0')),
                ('size', models.TextField(default='0')),
                ('source', models.CharField(max_length=5242880)),
                ('album', models.TextField(default='')),
                ('album_photo', models.CharField(max_length=65536)),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_id', to='FaMusic.user')),
            ],
        ),
    ]
