# Generated by Django 3.2.7 on 2021-10-31 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(default='', max_length=32)),
                ('nick_name', models.CharField(default='', max_length=255)),
                ('password', models.CharField(default='', max_length=255)),
                ('head_photo', models.ImageField(upload_to='images/head_photo')),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=255)),
                ('artist', models.CharField(default='', max_length=255)),
                ('duration', models.IntegerField(default=0)),
                ('size', models.IntegerField(default=0)),
                ('source', models.BinaryField(max_length=5242880)),
                ('album', models.CharField(default='', max_length=255)),
                ('album_photo', models.ImageField(upload_to='images/album')),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_id', to='FaMusic.user')),
            ],
        ),
    ]
